services:
  osrm:
    image: osrm/osrm-backend
    platform: linux/amd64
    ports:
      - "5501:5000"
    volumes:
      - ./data:/data
    command: >
      osrm-routed --algorithm mld /data/chile-latest.osrm