# Generated by Django 6.0.6 on 2026-06-22 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0001_initial"),
        ("optimization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routingconfig",
            name="max_route_time_sec",
            field=models.IntegerField(
                default=10800, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="routingconfig",
            name="min_route_time_sec",
            field=models.IntegerField(
                default=7200, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="routingconfig",
            name="service_time_sec",
            field=models.IntegerField(
                default=300, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="routingconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_route_time_sec__gte", 1)),
                name="routingconfig_min_route_time_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_route_time_sec__gte", 1)),
                name="routingconfig_max_route_time_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("service_time_sec__gte", 1)),
                name="routingconfig_service_time_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_route_time_sec__gte", models.F("min_route_time_sec"))
                ),
                name="routingconfig_max_route_time_gte_min",
            ),
        ),
    ]
