# Generated by Django 6.0.6 on 2026-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0002_alter_routingconfig_max_route_time_sec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingconfig",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("spatial_term", "Spatial Term"),
                    ("cluster_first", "Cluster First"),
                ],
                default="global",
                max_length=20,
            ),
        ),
    ]
