# Generated by Django 6.0.6 on 2026-06-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0005_routingsolution_unique_job_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingsolution",
            name="interleave_per_route",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="routingsolution",
            name="interleave_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="routingsolution",
            name="sum_max_radius_m",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="routingsolution",
            name="worst_pair_iou",
            field=models.FloatField(default=0),
        ),
    ]
