# Generated by Django 6.0.6 on 2026-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0010_optimizationjob_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingsolution",
            name="timing",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
