# Generated by Django 6.0.6 on 2026-07-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0011_routingsolution_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optimizationjob",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("spatial_term", "Spatial Term"),
                    ("cluster_first", "Cluster First"),
                    ("compare", "Compare"),
                ],
                default="spatial_term",
                max_length=20,
            ),
        ),
    ]
