# Generated by Django 6.0.6 on 2026-07-26 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0013_alter_routingconfig_service_time_sec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routingconfig",
            name="service_time_sec",
            field=models.IntegerField(
                default=120, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
