# Generated by Django 6.0.6 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0014_alter_routingconfig_service_time_sec"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationjob",
            name="config_preset",
            field=models.CharField(
                choices=[
                    ("default", "Equilibrada"),
                    ("temporal_span_100", "Rutas más parejas"),
                    ("arc_linear_30", "Menos zigzag"),
                ],
                default="default",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="routingsolution",
            name="degenerate_routes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="routingsolution",
            name="dropped_trees",
            field=models.IntegerField(default=0),
        ),
    ]
