# Generated by Django 6.0.6 on 2026-08-03 04:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0005_remove_routestop_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="geometry",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
