# Generated by Django 6.0.6 on 2026-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("surveyor", "Censista")],
                default="surveyor",
                max_length=20,
            ),
        ),
    ]
